---
- name: Add Pritunl repository.
  yum_repository:
    name: pritunl
    description: Pritunl Repository
    baseurl: https://repo.pritunl.com/stable/yum/centos/{{ ansible_distribution_major_version }}/
    gpgcheck: no
    enabled: no

- name: Ensure Pritunl is installed.
  yum:
    name: pritunl
    enablerepo: epel,pritunl

# service
- name: Ensure Pritunl is started and enabled to start at boot.
  service: name=pritunl state=started enabled=yes
  when: ansible_connection != 'docker'

# clean up
- name: Purge yum cache.
  command: yum clean all
  when: ansible_connection == 'docker'
